name: SemVer Release Workflow

run-name: "Releasing ${{ github.event.repository.name }} #${{github.run_number}}"

# Trigger workflow manually
on:
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.ref_name }}
  TRUNK_BRANCH_NAME: ${{ github.event.repository.default_branch }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    if: github.repository_owner == 'ikmdev'
    steps:
      - name: Verify Branch
        if: env.BRANCH_NAME != env.TRUNK_BRANCH_NAME
        run: |
          echo "ERROR: Attempting to release from branch ${{ env.BRANCH_NAME }}. Release from ${{ env.TRUNK_BRANCH_NAME }} branch only."
          exit 1

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{secrets.IKMDEVOPS_PAT_TOKEN}}

      - name: Verify Version
        run: |
            CURRENT_VERSION=$(./mvnw help:evaluate -D'expression=project.version' -q -D'forceStdout')
            CORE_VERSION=$(./mvnw help:evaluate -D'expression=core.artifact.version' -q -D'forceStdout')
            if [[ "$CURRENT_VERSION" != *"$CORE_VERSION"* ]]; then
               echo "::error::Current Version Does Not Match Core Version"
               echo "::error::Current Version: $CURRENT_VERSION"
               echo "::error::Core Version: $CORE_VERSION"
               exit 1
            fi

      - name: Shared Release Action
        uses: ikmdev/maven-semver-release-action@v2
        with:
          version_type: 'pre-release'
          github_token: ${{secrets.GITHUB_TOKEN}}

      - name: New Release Property
        id: new_release_property
        shell: bash
        run: |
           echo "VERSION=$(mvn help:evaluate -D'expression=project.version' -q -D'forceStdout')"
           IFS='-'
           read -ra arr <<< "$VERSION"
           for val in "${arr[@]}"
             do
               if [[ $val == r* ]]; then
                   RELEASE_PROPERTY=$val
               fi
             done
            echo "$RELEASE_PROPERTY"
            echo "::set-output name=PROPERTY::$RELEASE_PROPERTY"

      - name: Update Release Candidate Property
        run: |
          mvn versions:set-property \
            -Dproperty=core.artifact.release \
            -DnewVersion=$RELEASE_PROPERTY
             git config user.name "ikmdevops"
             git config user.email "devops@ikm.dev"
             git pull -p
             git commit -am"Updated Release core.artifact.release Property to $RELEASE_PROPERTY"
             git push
        env:
         RELEASE_PROPERTY: ${{steps.new_release_property.outputs.PROPERTY}}